[general]
use_julia_native_enum_type = true
print_using_CEnum = false
library_name = "libprimac"

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"
add_comment_for_skipped_macro = true
