name: Test g95 for the solvers

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 5 * * *'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  # check_date:
  #   runs-on: ubuntu-latest
  #   name: Check latest commit
  #   outputs:
  #     has_recent_commit: ${{ steps.has_recent_commit.outputs.has_recent_commit }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: print latest_commit
  #       run: echo ${{ github.sha }}
  #     - id: has_recent_commit
  #       continue-on-error: true
  #       name: check whether the last commit is sufficiently recent
  #       if: ${{ github.event_name == 'schedule' }}
  #       run: if [[ -n $(git rev-list  --after="6 hours"  ${{ github.sha }}) ]] ; then echo "::set-output name=has_recent_commit::true"; fi


  test:
    name: Run g95 tests
    runs-on: ${{ matrix.os }}
    #needs: check_date
    #if: ${{ github.event_name != 'schedule' || needs.check_date.outputs.has_recent_commit == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        # As of 20210918, according to https://github.com/actions/virtual-environments ,
        # ubuntu-latest = ubuntu-20.04,
        # macos-latest = macos-10.15,
        # windows-latest = windows-2019
        #os: [ubuntu-latest, ubuntu-18.04]
        os: [ubuntu-latest]
        bitness: [32, 64]
        #ikind: [i2, i4, i8]
        solver: [lincoa, bobyqa, uobyqa]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g95
        run: |
          bash .github/scripts/install_g95

      - name: Make sed available on Windows
        if: runner.os == 'Windows'
        run: $env:Path += ";C:\Program Files\Git\usr\bin"

      - name: Set environment variables
        run: |
          TEST_DIR=/tmp/gittest_"$(date +%s)"_"$((RANDOM*RANDOM))"  # Needed in the Makefiles
          echo "TEST_DIR=$TEST_DIR" >> $GITHUB_ENV  # Make the environment variable available in subsequent steps
          echo "$TEST_DIR"

      - name: Conduct the test
        run: |
          # No need to test in parallel, as 9test compiles without running (identical to 9test_c).
          source /tmp/setenv.sh
          ROOT=$(realpath ./)
          cd $ROOT/fsrc/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd $ROOT/fsrc/tests && make 9test_c.${{ matrix.solver }}
          # 20211012: make 9test_newuoa will not work, because, for some unknown reason, 9test_c is
          # remade when making 9test even though 9test_c has been made and up to date. Since the
          # making of 9test is in parallel, 9test_c will also be triggered in parallel, which leads
          # to problems like un-found modules. Not yet observed for other tests.

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TEST_DIR }}/fsrc/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run:
          rm -rf ${{ env.TEST_DIR }}
