name: Test armflang on Raspberry Pi

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 4 1-31/2 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run armflang tests
    runs-on: [self-hosted, ARM64, pi64]
    strategy:
      fail-fast: false
      matrix:
        ikind: [i2]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-O1, -O2, -O3, -g, -fast]
        testdim: [small, big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        run: |
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd "$ROOT_DIR"/fortran/tests
          if [[ -f "test_cobyla.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 110|g' test_cobyla.f90
          fi
          export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make rtest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make rtest

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
