name: Test gfortran, big

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 16 1-31/4 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run gfortran tests
    runs-on: ${{ matrix.os }}
    # As of 20230117, we must set max-parallel to 50 (not higher) and put macos-x as the last os(es).
    # Otherwise, the other jobs will not start until all the macos jobs finish, which will take much
    # time since the maximal concurrent number of macos jobs is 5. See
    # https://support.github.com/ticket/personal/0/1952095
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc]
        version: [12]
        ikind: [i2, i4]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-O1, -O2, -g, -fast]
        testdim: [big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Fortran
        id: setup_fortran
        uses: awvwgk/setup-fortran@main
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check Fortran compiler
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version
        shell: bash
        env:
          FC: ${{ steps.setup_fortran.outputs.fc }}
          CC: ${{ steps.setup_fortran.outputs.cc }}

      - name: Make tools such as grep, make, and git available on Windows
        if: runner.os == 'Windows'
        run: $env:Path += ";C:\Program Files\Git\usr\bin;C:\Program Files\Git\bin;C:\ProgramData\Chocolatey\bin"

      - name: Set miscellaneous environment variables
        shell: bash  # Important; otherwise, the following statements do not work on Windows.
        run: bash .github/scripts/misc_env

      - name: Conduct the test
        shell: bash  # Important; otherwise, `<` will not work on Windows.
        # Not sure whether the Makefile has bugs, but on Windows the making of gtest always invokes
        # the making of gtest_c twice even if the former is up to date after the first making. It
        # may lead to errors due to parallel making. To avoid this, we make gtest_c first.
        run: |
            ROOT="$(cd "$(dirname "./")"; pwd -P)/$(basename "./")"  # `realpath` is unavailable on macOS
            # 20221212: We skip the linting and extensive test on Windows due to the following
            # reasons. The example will still be tested on Windows.
            # 1. Windows does not support the symlink of linux, and hence mlint and flint do not work.
            # 2. Makefile.common does not work on Windows for the moment due to quotation marks.
            if [[ "$RUNNER_OS" != "Windows" ]] ; then
                export TESTDIM=${{ matrix.testdim }}
                export FFLAGS=${{ matrix.fflags }}
                cd "$ROOT"/fortran/tests && make gtest_${{ matrix.ikind }}_c.${{ matrix.solver }} && make gtest_${{ matrix.ikind }}.${{ matrix.solver }}
            fi

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        # Note that `$TEST_DIR` does not work on Windows, where its equivalent is `$env:TEST_DIR`.
        # In the following, we enquire `$TEST_DIR` by using the `env` context, which is platform independent.
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        shell: bash  # Important; otherwise, `rm -rf` will not work on Windows.
        run: rm -rf ${{ env.TEST_DIR }}
