name: Test Oracle sunf95

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    #  - cron: '0 7 * * *'
    - cron: '0 7 * * *'  # Reduce the frequency until NORM is fixed.
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run sunf95 tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 720  # The maximum number of minutes allowed to run the job.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ikind: [i2]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        # As of 20230213, -fast fails often; seems due to stack overflow. How to force sunf95 to use
        # heap only?
        fflags: [-O1, -O2, -O3, -g] #, -fast]
        testdim: [small, big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0
        with:
          submodules: recursive

      - name: Install Oracle sunf95
        run: bash .github/scripts/install_sunf95

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        run: |
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd "$ROOT_DIR"/fortran/tests
          if [[ -f "test_cobyla.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 90|g' test_cobyla.f90
          fi
          export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make stest_${{ matrix.ikind }}.${{ matrix.solver }}
          # sunf95 cannot handle matrix indexing with TRUELOC
          if [[ ! ${{ matrix.solver }}=='lincoa' && ! ${{ matrix.solver }}=='bobyqa' ]] ; then
              cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make stest
          fi

      - name: Store artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
